apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUmpiK3drdjZUUDR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeE1UY3dNRFEwTlRCYUZ3MHpOREF4TVRRd01EUTVOVEJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNwOVFhV1FyZ3NyYStBOWNqbUd4bU1uWkUwVjRLQ3NJaWhtS0xwdUhMbXQwdk1la0w5WkFZaS8wVk8Ka2RBdWRhTDZYWG1KU2JzOTg3THo5ZzRDUHRHbnA4NU8vY1JGSUFCM0pBNTlpcENvSVlkMTFxOEhCajhpMXVCWgpyL05ZTWxKa0E2eURjRXJ0YVN5aDNNVGtUYzFCc1ZmQWRyeXBYREhXNUtsMWVNR1JnQUovUzQveWNlMVlrT0M0CkNSd1JLMlFiZ1J3R3NMdFQwSXNwUWRob1Y4K080WDFmNUMrVXVNWExYYmZOYlBDcW1iSVpOL1czeVNtK25yZ0EKZS9sZWk0R29QNG9RS3JMWklhZjVRSTFVRjBuZFZZbkQrWWFvWUs1dWh1dU1nVTRyOHg3SGRYNEJEMDdDWDRXVApFRlhoKy8wa0V4QW1PbGhqU3Jxd2txSHZYUVBUQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRRkN3eG1oNWJCYnRpbDlZc1NUTDhOeU1LK2pEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXFxc0pDcGJvKwpQaUdQQ3pKUk96TzducUJDVWFLanYrZ0hWanFtU25MamxnaElNU3k2Uk40RElFMmdWcWE4Qmp0SjE2Q0lLOUtmCnZ1M2kyTlJYTlBaOWVUdWhzdU5NV2RYSUNKcUZvU004dnlMNzl1RlVZSjlEL0s0Q1p0bE9KbjdidERoTHUrWDcKVWgrK1RidkI3dG1CaVNqUC85NlR1WlZYTjhjazE2ZlA4STJsS0laekNsNWUvOTJxOHR0T1h0ancxcjl4QXV1VwpSWkVUOTRSSWpDakwwVGFMNjludFlmMlFLWXZQRndqU05YSmVEVXdMSlR0cHlyK015Z2NIcjhyRFR2b1ptNG1OCkUzUTBBeWxQdVAvTEJXNFFyVEI0Yyt0end0b1ZTc2kzZ2xOamExYTdwSEpqaWJ5bVpQbzQwMWxZRmo1OXB2WW4KWnY3QlN1eUtTWkFQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://DA09E7AF849029089D640749D9C4C8C7.sk1.ap-northeast-2.eks.amazonaws.com
  name: arn:aws:eks:ap-northeast-2:553186839963:cluster/education-eks-LHtapype
contexts:
- context:
    cluster: arn:aws:eks:ap-northeast-2:553186839963:cluster/education-eks-LHtapype
    user: arn:aws:eks:ap-northeast-2:553186839963:cluster/education-eks-LHtapype
  name: arn:aws:eks:ap-northeast-2:553186839963:cluster/education-eks-LHtapype
current-context: arn:aws:eks:ap-northeast-2:553186839963:cluster/education-eks-LHtapype
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-northeast-2:553186839963:cluster/education-eks-LHtapype
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-northeast-2
      - eks
      - get-token
      - --cluster-name
      - education-eks-LHtapype
      - --output
      - json
      command: aws
